/**
 * Fit Culture (https://www.ennapd.com/fitculture)
 *
 * Copyright © 2018-present Enappd. All rights reserved.
 *
 * This source code is licensed as per the terms found in the
 * LICENSE.md file in the root directory of this source tree.
 */
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {
  slideOpts = {
    loop: true,
    autoplay: {
      delay: 2000,
    },
  };

  showHeader: boolean;
  profile: any = [];
  ionViewWillEnter() {
    this.showHeader=true
  }
  constructor() { 
    this.showHeader = false;
    this.profile = [
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Noemi Brown",
        "gender": "F",
        "password": "password",
        "shortDesc": "labore",
        "longerDesc": "officia anim consectetur commodo",
        "type": "CUSTOMER",
        "bio": "Ullamco anim Lorem eu commodo fugiat commodo fugiat fugiat magna fugiat elit sit occaecat amet. Officia ullamco do duis mollit cillum ex. Do consequat irure laboris incididunt qui do proident nostrud. Ad in ullamco nostrud voluptate eu occaecat id.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 45
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery7.jpg",
        "name": "Oneal Kerry",
        "gender": "M",
        "password": "password",
        "shortDesc": "laborum",
        "longerDesc": "laborum culpa et pariatur",
        "type": "TRAINER",
        "bio": "Amet minim commodo do occaecat amet velit nisi laborum aliqua anim aliquip aliqua proident. Labore irure quis id consectetur elit nisi. Elit deserunt dolore ea eu nulla fugiat. Eiusmod laborum laboris deserunt in id quis in. Consequat ad officia nulla tempor duis consectetur non esse velit do fugiat consectetur sit amet. Consequat ipsum enim amet anim commodo deserunt nulla enim elit magna. Fugiat culpa et proident tempor anim consequat occaecat dolor.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 88
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery6.jpg",
        "name": "Chrystal Ratliff",
        "gender": "M",
        "password": "password",
        "shortDesc": "esse",
        "longerDesc": "laboris nostrud anim et",
        "type": "TRAINER",
        "bio": "Eu labore est est nulla. Ex amet incididunt incididunt nulla irure eiusmod culpa sit dolore velit qui culpa cillum. Aliquip dolor dolor aute ullamco dolor incididunt id. Nulla aliqua ad ullamco labore id eiusmod dolore incididunt id et veniam ullamco. Ex est duis sunt est consectetur ipsum sunt velit fugiat cupidatat dolore deserunt.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 118
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Verna Holloway",
        "gender": "M",
        "password": "password",
        "shortDesc": "duis",
        "longerDesc": "quis excepteur nostrud commodo",
        "type": "CUSTOMER",
        "bio": "Id ad pariatur ullamco pariatur proident elit quis id. Lorem magna et sunt voluptate excepteur ipsum cillum. Non aliqua dolore ipsum eu exercitation anim irure. Lorem duis nisi ut sunt Lorem tempor aliqua sint consequat cupidatat consequat laborum occaecat sint. Id do commodo sit dolore. Voluptate fugiat consequat id ex.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 54
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery4.jpg",
        "name": "Carrie Wilda",
        "gender": "M",
        "password": "password",
        "shortDesc": "sint",
        "longerDesc": "elit ut commodo aute",
        "type": "TRAINER",
        "bio": "Quis incididunt dolore deserunt ex sunt dolor consectetur occaecat in duis duis irure. Voluptate esse occaecat quis amet. Culpa sint nostrud culpa exercitation ut culpa. Aute velit reprehenderit amet anim veniam ad proident ea nisi.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 71
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery6.jpg",
        "name": "Gayle Young",
        "gender": "M",
        "password": "password",
        "shortDesc": "est",
        "longerDesc": "minim in deserunt cupidatat",
        "type": "CUSTOMER",
        "bio": "Cillum occaecat aliquip id fugiat in. Amet occaecat id ad ipsum nisi eu est amet cupidatat. Est mollit do ullamco tempor dolore duis sint voluptate laboris sunt ea ex. Magna elit commodo eiusmod aliquip tempor esse amet commodo officia ipsum ut. Culpa ut minim aliquip tempor consectetur nisi elit aute enim elit. Cupidatat ut aliqua ex incididunt irure mollit eiusmod elit in amet. Reprehenderit pariatur officia aliqua minim labore.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 115
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery3.jpg",
        "name": "Erin Socorro",
        "gender": "F",
        "password": "password",
        "shortDesc": "nulla",
        "longerDesc": "irure id duis culpa",
        "type": "CUSTOMER",
        "bio": "Amet excepteur duis sunt exercitation et est ut. Est aliquip enim voluptate culpa. Nulla reprehenderit in dolore id anim aliqua dolor deserunt deserunt esse nostrud. Eu do sunt eu laborum minim adipisicing consequat.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 1,
        "rate": 99
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery1.jpg",
        "name": "Harding Williams",
        "gender": "F",
        "password": "password",
        "shortDesc": "sint",
        "longerDesc": "excepteur adipisicing non reprehenderit",
        "type": "CUSTOMER",
        "bio": "Et sunt ut qui et anim laboris. Adipisicing nisi ut est veniam sunt exercitation dolore laborum labore ex sunt irure nulla. Nisi quis ut incididunt laboris velit aliquip aliqua incididunt eu ad adipisicing. Culpa consectetur consequat eu consequat laborum sint eu ex esse officia laborum officia.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 51
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Charmaine Mayo",
        "gender": "M",
        "password": "password",
        "shortDesc": "exercitation",
        "longerDesc": "voluptate pariatur ullamco dolore",
        "type": "TRAINER",
        "bio": "Fugiat anim cillum in ex ea proident pariatur. Eiusmod minim ex eiusmod culpa nulla laborum laboris tempor magna enim do voluptate. Pariatur enim ex adipisicing nulla sit. Consectetur mollit proident fugiat exercitation consectetur et. Et ex culpa enim aliquip commodo est sit elit veniam deserunt nostrud magna quis. Est ut cupidatat et ex laboris culpa dolore amet tempor aliquip dolor cupidatat ipsum sit.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 71
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery1.jpg",
        "name": "Lesley Bridget",
        "gender": "F",
        "password": "password",
        "shortDesc": "commodo",
        "longerDesc": "cillum laborum Lorem voluptate",
        "type": "TRAINER",
        "bio": "Qui enim amet dolore ad voluptate et in nulla ullamco ipsum deserunt dolor fugiat culpa. Deserunt exercitation duis commodo labore nostrud ipsum aliquip nostrud esse et do ea veniam. Do cupidatat laboris amet quis ex est consectetur ex proident labore nostrud anim. Ut id velit sint enim labore amet cillum ad laboris. Minim aliquip dolor do consequat aute cillum et ipsum do sunt.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 1,
        "rate": 78
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery8.jpg",
        "name": "Claudine Pope",
        "gender": "M",
        "password": "password",
        "shortDesc": "officia",
        "longerDesc": "enim cillum fugiat est",
        "type": "TRAINER",
        "bio": "Velit pariatur anim commodo Lorem laborum consectetur quis magna aliqua non nisi velit enim. Eu est sunt excepteur culpa occaecat irure enim dolor excepteur. Tempor anim tempor anim anim laboris cillum Lorem qui dolor. Esse sunt commodo sunt aliquip proident. Sint officia aliqua pariatur commodo dolor velit. Nulla mollit aliqua Lorem consectetur cupidatat culpa sit qui fugiat consequat. Incididunt adipisicing Lorem veniam sunt in Lorem ipsum.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 62
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery8.jpg",
        "name": "Sarah Kerr",
        "gender": "F",
        "password": "password",
        "shortDesc": "voluptate",
        "longerDesc": "sunt consequat id laboris",
        "type": "TRAINER",
        "bio": "Veniam anim aliquip veniam aliquip cillum esse officia occaecat nostrud non. Non consequat consequat eu incididunt adipisicing minim labore voluptate. Magna ipsum laborum eiusmod ut ea id occaecat. Aliqua sunt aliqua ea excepteur in deserunt Lorem eiusmod exercitation tempor. Cillum ad ad voluptate anim laborum deserunt. Enim quis velit reprehenderit elit mollit cupidatat consequat elit ea adipisicing culpa dolore id.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 54
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery6.jpg",
        "name": "Whitney Wilder",
        "gender": "F",
        "password": "password",
        "shortDesc": "ad",
        "longerDesc": "labore ad aliquip sit",
        "type": "TRAINER",
        "bio": "Lorem amet reprehenderit nostrud laborum. Ullamco quis et velit exercitation qui labore irure. Ex Lorem dolore anim ea ad qui nulla. Pariatur commodo elit est consequat minim.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 104
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery3.jpg",
        "name": "Richardson Merritt",
        "gender": "F",
        "password": "password",
        "shortDesc": "incididunt",
        "longerDesc": "ea amet ea irure",
        "type": "TRAINER",
        "bio": "Qui et duis ea do non. Sint do in labore est cupidatat. In veniam exercitation occaecat cupidatat fugiat eu id fugiat. Lorem proident magna voluptate irure aute. Ea eiusmod tempor veniam ullamco proident. Ullamco proident nulla incididunt proident quis cupidatat dolore in proident. In ea non commodo veniam et magna consectetur fugiat enim.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 117
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Crane Gilmore",
        "gender": "F",
        "password": "password",
        "shortDesc": "ad",
        "longerDesc": "amet eu eiusmod anim",
        "type": "TRAINER",
        "bio": "Mollit eiusmod consequat sunt in ut Lorem commodo et sint nisi. Mollit tempor nulla laboris nostrud reprehenderit labore aliqua cupidatat aute. Consectetur et commodo irure ad pariatur eiusmod quis ex voluptate incididunt dolor adipisicing occaecat. Nulla ea enim commodo in qui cillum non.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 143
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery7.jpg",
        "name": "Callahan Freeman",
        "gender": "F",
        "password": "password",
        "shortDesc": "ut",
        "longerDesc": "elit magna magna pariatur",
        "type": "TRAINER",
        "bio": "Do excepteur nostrud consectetur minim. Dolore qui est magna est excepteur est anim ipsum mollit incididunt adipisicing sint laborum dolor. Sunt culpa minim pariatur consequat non cupidatat ullamco occaecat mollit consectetur. Nostrud duis qui do anim magna sunt ullamco dolore sunt consequat eiusmod eiusmod enim in. Incididunt enim et cupidatat sit nostrud ullamco dolore labore voluptate dolore.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 2,
        "rate": 81
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Ernestine Polly",
        "gender": "M",
        "password": "password",
        "shortDesc": "anim",
        "longerDesc": "occaecat do velit est",
        "type": "CUSTOMER",
        "bio": "Id culpa aliquip quis commodo eiusmod exercitation voluptate. Cupidatat labore esse duis amet laborum non aliqua sunt esse ullamco amet excepteur. Aute id reprehenderit aliquip tempor deserunt veniam ullamco proident elit culpa irure qui. Nostrud laborum veniam in qui Lorem. Non occaecat incididunt sit nulla non. Ipsum duis cillum proident magna exercitation sunt ea nisi aliquip tempor.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 136
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery1.jpg",
        "name": "Bianca Hansen",
        "gender": "F",
        "password": "password",
        "shortDesc": "eiusmod",
        "longerDesc": "non sit aliqua aliquip",
        "type": "CUSTOMER",
        "bio": "Enim id ipsum nulla excepteur ipsum amet elit. Consectetur Lorem culpa reprehenderit laboris aliquip dolor ut cillum do eiusmod. Labore mollit laborum sunt enim irure dolor aliqua non incididunt.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 42
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery1.jpg",
        "name": "Maude Long",
        "gender": "M",
        "password": "password",
        "shortDesc": "Lorem",
        "longerDesc": "ut irure aute excepteur",
        "type": "TRAINER",
        "bio": "Nisi adipisicing reprehenderit amet dolor do enim nisi consequat commodo incididunt laboris labore. Id fugiat reprehenderit amet eiusmod pariatur sit ut qui consectetur consequat laborum. Sint sint et eu veniam enim est aute ea mollit. Ea aute cillum id Lorem Lorem et consectetur aute officia amet laboris ipsum laborum ad. Quis adipisicing ea fugiat excepteur elit id cupidatat do. Ullamco irure occaecat sint fugiat nisi eu minim qui est qui enim.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 58
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery1.jpg",
        "name": "Stokes Etta",
        "gender": "M",
        "password": "password",
        "shortDesc": "sit",
        "longerDesc": "cillum aliqua sint ad",
        "type": "CUSTOMER",
        "bio": "Eu amet laboris incididunt velit ipsum nulla. Amet officia consectetur ullamco magna. Lorem velit non do duis laboris tempor voluptate. Occaecat aliquip labore in proident ipsum commodo.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 106
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery7.jpg",
        "name": "Suarez Henson",
        "gender": "F",
        "password": "password",
        "shortDesc": "dolor",
        "longerDesc": "nostrud officia nulla ex",
        "type": "CUSTOMER",
        "bio": "Ad dolore ipsum laboris minim veniam quis incididunt incididunt qui ipsum commodo officia veniam. Cupidatat quis cillum eiusmod laboris dolore sint occaecat. Qui tempor fugiat sit pariatur ullamco. Pariatur incididunt elit do quis reprehenderit. Eiusmod deserunt cillum ut sit ex proident eu occaecat et cupidatat aute culpa velit. In in ut proident eu anim eiusmod.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 143
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Frederick Brittany",
        "gender": "M",
        "password": "password",
        "shortDesc": "sunt",
        "longerDesc": "velit laborum eiusmod nisi",
        "type": "TRAINER",
        "bio": "Laborum aute ullamco labore commodo incididunt amet adipisicing. Laborum est ullamco nisi dolore do aliqua dolor consectetur officia adipisicing eiusmod. Irure exercitation culpa sit quis minim magna.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 2,
        "rate": 144
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Holland Goff",
        "gender": "F",
        "password": "password",
        "shortDesc": "pariatur",
        "longerDesc": "laboris occaecat ipsum proident",
        "type": "CUSTOMER",
        "bio": "Consectetur ullamco do ad in do ad reprehenderit velit ut sunt. Dolore amet proident Lorem ex sint qui est veniam pariatur cillum mollit duis aliquip. Aliqua non commodo excepteur ut esse Lorem in dolore mollit. Ut mollit culpa amet exercitation labore culpa duis et.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 106
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Keith Webster",
        "gender": "M",
        "password": "password",
        "shortDesc": "ut",
        "longerDesc": "ad aliqua minim aute",
        "type": "CUSTOMER",
        "bio": "Consequat ad et cupidatat qui Lorem anim. Esse ea velit velit sint irure nostrud. Quis quis proident tempor eiusmod est ut reprehenderit tempor sint amet dolor enim.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 110
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Cameron Brianna",
        "gender": "F",
        "password": "password",
        "shortDesc": "quis",
        "longerDesc": "fugiat velit veniam velit",
        "type": "CUSTOMER",
        "bio": "Aute sint ex excepteur nulla aliquip pariatur Lorem irure anim culpa aute et nulla culpa. Adipisicing nostrud velit quis proident irure laboris aute occaecat. Ipsum est voluptate commodo sint laboris culpa fugiat veniam proident aliquip. Eiusmod et ea laboris nisi adipisicing sunt eu excepteur labore sit aute do minim aliqua. Laboris et irure proident non cupidatat do anim. Aute id veniam minim aute aliquip amet id excepteur dolore.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 52
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery4.jpg",
        "name": "Mcclain Joann",
        "gender": "M",
        "password": "password",
        "shortDesc": "cupidatat",
        "longerDesc": "enim culpa eiusmod sunt",
        "type": "TRAINER",
        "bio": "Aliqua occaecat aute consectetur qui. Sint id labore et proident sit fugiat consectetur sit anim. Do ea culpa cillum ad eu. Ipsum est aute pariatur elit ad excepteur minim labore.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 42
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Green Sanchez",
        "gender": "F",
        "password": "password",
        "shortDesc": "adipisicing",
        "longerDesc": "quis esse dolore ad",
        "type": "TRAINER",
        "bio": "Occaecat aliquip adipisicing irure irure irure ex irure ex ad tempor officia duis consequat. Lorem id magna enim amet incididunt eiusmod eu ea ipsum dolore minim velit incididunt. Ipsum non voluptate eu nostrud ea exercitation velit incididunt ad nulla incididunt. Sit cillum occaecat nulla occaecat incididunt veniam minim sint ad. Nostrud voluptate nisi Lorem minim ea consectetur. Est esse minim esse incididunt mollit ex amet aliquip. Anim velit laborum amet nostrud reprehenderit.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 45
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery4.jpg",
        "name": "Beverley Kirsten",
        "gender": "M",
        "password": "password",
        "shortDesc": "labore",
        "longerDesc": "id officia amet aliqua",
        "type": "TRAINER",
        "bio": "Incididunt officia cupidatat adipisicing cillum qui occaecat anim consequat exercitation velit. Quis mollit Lorem in veniam. Eiusmod in mollit elit dolor.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 140
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery8.jpg",
        "name": "Murray Helga",
        "gender": "M",
        "password": "password",
        "shortDesc": "est",
        "longerDesc": "anim quis adipisicing sunt",
        "type": "CUSTOMER",
        "bio": "Proident do cillum nostrud aliqua. Reprehenderit sint exercitation exercitation enim. Incididunt minim amet tempor officia dolore. Ipsum et proident incididunt eiusmod dolor id in mollit ea cillum velit officia. Exercitation id ipsum proident incididunt reprehenderit ea ex. Elit culpa Lorem mollit nulla irure. Duis sunt duis enim fugiat velit ea in nisi reprehenderit.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 61
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery3.jpg",
        "name": "Odessa Sandoval",
        "gender": "F",
        "password": "password",
        "shortDesc": "elit",
        "longerDesc": "elit consequat veniam consequat",
        "type": "CUSTOMER",
        "bio": "Culpa tempor quis ullamco sunt non do consectetur. Ullamco commodo proident sunt velit adipisicing nulla laborum proident sint et. Lorem Lorem reprehenderit eu amet exercitation.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 57
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery6.jpg",
        "name": "Esther Ellis",
        "gender": "M",
        "password": "password",
        "shortDesc": "ut",
        "longerDesc": "sunt magna cillum culpa",
        "type": "CUSTOMER",
        "bio": "Pariatur non minim incididunt sunt laboris reprehenderit sunt veniam cillum ipsum magna occaecat elit eiusmod. Nostrud sunt deserunt veniam ipsum cillum quis. Labore id adipisicing sunt incididunt ea cillum amet ea anim nostrud. Sint elit labore dolor qui mollit pariatur. Ipsum reprehenderit labore nostrud dolor minim reprehenderit aliqua. Officia ad et aliquip qui adipisicing culpa ut dolor id.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 81
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Marian Macdonald",
        "gender": "F",
        "password": "password",
        "shortDesc": "magna",
        "longerDesc": "deserunt veniam irure fugiat",
        "type": "TRAINER",
        "bio": "Eiusmod elit adipisicing eiusmod veniam veniam ullamco id quis aliqua esse adipisicing. Sit Lorem nostrud non fugiat sit elit id exercitation irure aliqua. Fugiat proident labore nisi ullamco. Nisi commodo proident voluptate commodo nisi officia veniam eiusmod anim.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 102
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Cherie Wooten",
        "gender": "F",
        "password": "password",
        "shortDesc": "sint",
        "longerDesc": "amet in duis aute",
        "type": "TRAINER",
        "bio": "Nulla elit irure pariatur dolor eiusmod aute consequat proident est laborum aliqua. Exercitation aute culpa nostrud sit aliquip non sit nulla elit non anim reprehenderit ad nostrud. Irure excepteur sit eiusmod occaecat sint nisi aliqua nulla duis do esse excepteur. Mollit reprehenderit reprehenderit id excepteur eiusmod. Culpa enim culpa aute do deserunt occaecat non proident est ipsum. Incididunt voluptate anim magna reprehenderit esse commodo magna velit esse ipsum irure. Qui est mollit minim aliquip veniam sunt consectetur voluptate commodo consequat aliqua.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 116
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery3.jpg",
        "name": "Dixie Ingrid",
        "gender": "F",
        "password": "password",
        "shortDesc": "Lorem",
        "longerDesc": "anim sunt labore ea",
        "type": "CUSTOMER",
        "bio": "Id magna aute consequat in ut mollit est adipisicing veniam excepteur eu do. Enim aliquip Lorem qui in. Id qui veniam amet excepteur non occaecat. Non duis nostrud ut consequat velit excepteur veniam.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 2,
        "rate": 40
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery6.jpg",
        "name": "Larsen Odom",
        "gender": "F",
        "password": "password",
        "shortDesc": "excepteur",
        "longerDesc": "sit in consectetur duis",
        "type": "CUSTOMER",
        "bio": "Culpa elit adipisicing ea duis do ipsum. Dolor quis aute dolore voluptate ad ex. Exercitation aliquip cillum proident labore velit mollit ad Lorem proident sunt ea. Sunt elit dolor reprehenderit labore nostrud. Cillum magna nulla excepteur velit aute quis ut magna exercitation et.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 2,
        "rate": 147
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery7.jpg",
        "name": "Washington Suzette",
        "gender": "F",
        "password": "password",
        "shortDesc": "esse",
        "longerDesc": "nostrud sit elit officia",
        "type": "CUSTOMER",
        "bio": "Sint aliqua eiusmod tempor magna elit fugiat. Nulla irure laborum id consectetur. Enim officia sint veniam anim. Consectetur Lorem do cillum eiusmod aliqua elit officia laboris voluptate ex magna.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 2,
        "rate": 72
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery3.jpg",
        "name": "Kristi Knox",
        "gender": "M",
        "password": "password",
        "shortDesc": "aute",
        "longerDesc": "enim minim non culpa",
        "type": "CUSTOMER",
        "bio": "Incididunt commodo et velit quis et eiusmod esse sunt. Esse sint dolor consequat pariatur incididunt ex occaecat irure proident nulla ex. Velit veniam irure laboris eu amet occaecat veniam magna. Ex excepteur amet velit aute proident pariatur excepteur cillum aliquip nostrud tempor.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 145
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Morrow Shirley",
        "gender": "M",
        "password": "password",
        "shortDesc": "sint",
        "longerDesc": "tempor voluptate ad in",
        "type": "CUSTOMER",
        "bio": "Dolor ea ut dolor minim duis cillum est esse dolore incididunt mollit nostrud proident. Commodo eu id irure elit magna officia exercitation sit reprehenderit adipisicing tempor. Consequat ut magna laborum enim ipsum qui excepteur magna nisi. Est ex sit fugiat id occaecat voluptate enim excepteur nostrud aliqua nulla reprehenderit. Exercitation dolore enim eiusmod fugiat veniam minim labore aliqua eu aliqua fugiat sunt. Duis laboris anim aliqua aute duis cupidatat reprehenderit id. Est anim qui nisi tempor dolore pariatur in ad Lorem.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 114
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Calderon Eloise",
        "gender": "M",
        "password": "password",
        "shortDesc": "ad",
        "longerDesc": "culpa nostrud est laboris",
        "type": "CUSTOMER",
        "bio": "Excepteur duis ut sint labore non proident duis anim consectetur sint duis officia dolor ut. Excepteur cupidatat cupidatat officia est proident. Pariatur dolore nisi aute enim dolor aliqua anim cupidatat non et velit ipsum amet. Excepteur magna dolore quis commodo cupidatat ex dolore cillum occaecat aute. Ea proident officia fugiat enim sint et ad labore adipisicing. Deserunt est tempor adipisicing duis enim anim occaecat commodo. Qui esse sit commodo eiusmod veniam.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 55
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery4.jpg",
        "name": "Sallie Fitzgerald",
        "gender": "F",
        "password": "password",
        "shortDesc": "cupidatat",
        "longerDesc": "incididunt do occaecat consequat",
        "type": "CUSTOMER",
        "bio": "Quis laboris non mollit laboris dolor cillum non dolore tempor. Laborum dolore dolor sint culpa reprehenderit in mollit excepteur fugiat labore mollit deserunt sint magna. Aute ea eiusmod ipsum nostrud ut. Sint sint laborum ex dolor enim ea ea dolor ullamco anim voluptate dolore veniam. Lorem ex sunt est cupidatat est qui sunt culpa amet aliquip voluptate ipsum. Aliqua velit elit sunt sit. Laboris ullamco consequat minim amet enim tempor velit occaecat cupidatat mollit.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 4,
        "rate": 61
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery7.jpg",
        "name": "Patton Amparo",
        "gender": "M",
        "password": "password",
        "shortDesc": "voluptate",
        "longerDesc": "nostrud magna mollit est",
        "type": "CUSTOMER",
        "bio": "Nulla duis et pariatur nulla esse excepteur in cillum amet. Laboris ullamco nostrud adipisicing sint proident deserunt consequat commodo ullamco. Ex incididunt enim pariatur dolor.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 110
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery8.jpg",
        "name": "Alta Ericka",
        "gender": "F",
        "password": "password",
        "shortDesc": "non",
        "longerDesc": "ipsum ad magna proident",
        "type": "TRAINER",
        "bio": "Adipisicing incididunt magna nulla qui pariatur quis culpa amet reprehenderit ullamco sint eu aliqua. Mollit sunt dolore non irure cupidatat. Fugiat duis nisi nisi aliqua laborum laboris tempor qui consectetur.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 1,
        "rate": 90
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery7.jpg",
        "name": "Terra Gallegos",
        "gender": "F",
        "password": "password",
        "shortDesc": "ullamco",
        "longerDesc": "ad non deserunt aute",
        "type": "TRAINER",
        "bio": "Irure duis et ea consectetur consectetur incididunt cupidatat minim esse sunt amet. Officia sint tempor est amet voluptate quis culpa. Consectetur enim quis cupidatat sint magna elit. Officia minim in et in. Non magna id nisi aute voluptate non minim ut. Nulla magna reprehenderit enim duis.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 82
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery6.jpg",
        "name": "Aline Mercedes",
        "gender": "M",
        "password": "password",
        "shortDesc": "duis",
        "longerDesc": "cillum veniam consectetur do",
        "type": "CUSTOMER",
        "bio": "Commodo mollit nulla deserunt nisi sit amet aute occaecat sint consectetur enim deserunt reprehenderit esse. Lorem eu proident aute officia anim ea sunt. Proident dolore laborum dolor do eiusmod enim commodo laboris in ut commodo.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 2,
        "rate": 66
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Atkins Kristen",
        "gender": "F",
        "password": "password",
        "shortDesc": "proident",
        "longerDesc": "duis enim reprehenderit elit",
        "type": "TRAINER",
        "bio": "Cupidatat amet officia ut quis occaecat ex ea duis consequat. Eu aute sint voluptate dolore aute labore officia dolor reprehenderit culpa consectetur quis. Aute reprehenderit veniam esse ullamco enim ex incididunt ut eiusmod enim est. Deserunt et exercitation est laborum eiusmod laborum duis sit cupidatat labore quis. Cillum do magna reprehenderit dolore officia. Ipsum non aute duis ullamco. Aute dolore fugiat duis anim ullamco mollit culpa do consequat mollit Lorem non occaecat dolore.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 3,
        "rate": 117
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Pena Bonita",
        "gender": "M",
        "password": "password",
        "shortDesc": "enim",
        "longerDesc": "id culpa ex in",
        "type": "CUSTOMER",
        "bio": "In commodo ut pariatur ullamco id excepteur quis deserunt laboris cillum esse ullamco amet. Est minim enim dolore deserunt aliqua eu commodo cillum magna adipisicing. Eiusmod ea adipisicing reprehenderit minim exercitation aliqua velit et Lorem.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 99
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery3.jpg",
        "name": "Mamie Casey",
        "gender": "M",
        "password": "password",
        "shortDesc": "officia",
        "longerDesc": "minim occaecat consequat laboris",
        "type": "TRAINER",
        "bio": "Eiusmod minim culpa adipisicing reprehenderit enim commodo do elit ipsum laborum. Non excepteur ex deserunt amet in et minim dolore eu amet amet eiusmod. Amet enim dolore officia minim ad aliquip quis nulla nulla qui culpa. Excepteur cupidatat dolore nisi quis proident eu voluptate proident. Eu ad qui laboris reprehenderit aute et. Qui ad consectetur elit consequat nisi elit consectetur est deserunt et magna do velit cillum. Ea et dolore ad cupidatat consequat tempor adipisicing laboris sint sit.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 1,
        "rate": 90
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery6.jpg",
        "name": "Norton Warren",
        "gender": "M",
        "password": "password",
        "shortDesc": "in",
        "longerDesc": "sit proident id labore",
        "type": "CUSTOMER",
        "bio": "Eiusmod veniam consectetur Lorem nostrud qui ut quis deserunt mollit dolor dolore laborum. Adipisicing laboris amet pariatur non exercitation sit id labore ad aute ut exercitation. Exercitation ipsum reprehenderit excepteur labore cupidatat. Minim ullamco fugiat mollit labore. Sit dolore cupidatat enim amet quis. Eu cupidatat incididunt ut cillum fugiat deserunt. Aute eu et commodo ullamco consequat.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 2,
        "rate": 135
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery2.jpg",
        "name": "Bentley Wagner",
        "gender": "F",
        "password": "password",
        "shortDesc": "dolor",
        "longerDesc": "culpa anim tempor enim",
        "type": "TRAINER",
        "bio": "Eiusmod qui enim sint eu. Id eiusmod aliqua proident ullamco laboris ad aliquip eu qui mollit reprehenderit ex adipisicing. Aute non veniam occaecat proident exercitation amet. Incididunt dolore aute sit reprehenderit esse commodo elit deserunt consequat id dolor.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 5,
        "rate": 90
      },
      {
        "isActive": true,
        "image": "../assets/imgs/gallery5.jpg",
        "name": "Nadine Lamb",
        "gender": "F",
        "password": "password",
        "shortDesc": "eiusmod",
        "longerDesc": "tempor officia esse ad",
        "type": "CUSTOMER",
        "bio": "Duis ut magna cupidatat deserunt. Sint pariatur aliqua velit quis magna commodo pariatur proident. Proident aliquip dolore esse ullamco amet id eiusmod commodo ea eiusmod irure aute ad quis.",
        "email": "undefined.undefined@capbpm.com",
        "ratingScore": 1,
        "rate": 74
      }
    ]
  }

  ngOnInit() {
  }
}



